In [1]:
#mnist.pyの読み込み

In [2]:
import sys, os
sys.path.append(os.pardir)
from dataset.mnist import load_mnist

In [3]:
#import sys, os  import sysで探索する範囲を拡張しますという意味。osは親フォルダ。
#sys.path.append(os.pardir) そのフォルダのパスを指定。　os.pardirは親ファイルという意味。
#from dataset.mnist import load_mnist　　 datasetフォルダのminstからimport ministを読み込みましたよということ。

In [4]:
(x_train, t_train), (x_test, t_test) = \
 load_mnist(flatten=True, normalize=False)

In [5]:
print(x_train.shape)
print(t_train.shape)
print(x_test.shape)
print(t_test.shape)

(60000, 784)
(60000,)
(10000, 784)
(10000,)


In [6]:
#MINSTの画像を表示させる。

In [7]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from dataset.mnist import load_mnist
from PIL import Image
def img_show(img):
    pil_img=Image.fromarray(np.uint8(img))
    pil_img.show()
(x_train, t_train), (x_test, t_test) = \
 load_mnist(flatten=True, normalize=False)

In [8]:
img =x_train[0]
label=t_train[0]
print(label)

5


In [9]:
print(img.shape)

(784,)


In [10]:
img=img.reshape(28,28)
img_show(img)

In [11]:
#いよいよディープラーニングの出力層の設計を行う。まずは関数の定義

In [42]:
import pickle
def sigmoid(x):
    return 1/(1+np.exp(-x))

def softmax(a):
    c =np.max(a)
    exp_a =np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y =exp_a/sum_exp_a
    
    return y


def get_data():
    (x_train, t_train), (x_test, t_test) = \
    load_mnist(flatten=True, normalize=True,one_hot_label=False)
    return x_test,t_test
def init_networtk():
    with open("sample_weight.pkl", 'rb') as f :
        network = pickle.load(f)
        
    return network
def predict(network,x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1,   b2,   b3 = network['b1'], network['b2'],   network['b3']
    
    a1=np.dot(x,W1) + b1
    z1=sigmoid(a1)
    a2=np.dot(z1,W2) + b2
    z2=sigmoid(a2)
    a3=np.dot(z2,W3) + b3
    y=softmax(a3)
    
    return y

In [43]:
#データの呼び出し

In [44]:
x,t = get_data()
network = init_networtk()

In [45]:
#精度の検定

In [46]:
accuracy_cnt=0
for i in range(len(x)):
    y = predict(network, x[i])
    p = np.argmax(y)
    if p == t[i]:
        accuracy_cnt += 1
print("Accuracy:" + str(float(accuracy_cnt) / len(x)))

Accuracy:0.9352


In [48]:
#ここからはバッチ処理の実装

In [49]:
x = np.array([[0.1,0.8,0.1],[0.3,0.1,0.6],[0.2,0.5,0.3],[0.8,0.1,0.1]])

In [50]:
x

array([[ 0.1,  0.8,  0.1],
       [ 0.3,  0.1,  0.6],
       [ 0.2,  0.5,  0.3],
       [ 0.8,  0.1,  0.1]])

In [52]:
y=np.max(x,axis=1) #ここの軸がひっくり返っているのが意味わっかんねー
y

array([ 0.8,  0.6,  0.5,  0.8])

In [53]:
y=np.max(x,axis=0)
y

array([ 0.8,  0.8,  0.6])

In [55]:
y=np.argmax(x,axis=1)

In [56]:
import pickle
def sigmoid(x):
    return 1/(1+np.exp(-x))

def softmax(a):
    c =np.max(a)
    exp_a =np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y =exp_a/sum_exp_a
    
    return y


def get_data():
    (x_train, t_train), (x_test, t_test) = \
    load_mnist(flatten=True, normalize=True,one_hot_label=False)
    return x_test,t_test
def init_networtk():
    with open("sample_weight.pkl", 'rb') as f :
        network = pickle.load(f)
        
    return network
def predict(network,x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1,   b2,   b3 = network['b1'], network['b2'],   network['b3']
    
    a1=np.dot(x,W1) + b1
    z1=sigmoid(a1)
    a2=np.dot(z1,W2) + b2
    z2=sigmoid(a2)
    a3=np.dot(z2,W3) + b3
    y=softmax(a3)
    
    return y

In [57]:
#ここからがバッチ処理

In [58]:
x,t = get_data()
network = init_networtk()

In [59]:
batch_size =100
accuracy_cnt=0

for i in range(0,len(x),batch_size):
    x_batch= x[i:i+batch_size]
    y_batch=predict(network, x_batch)
    p =np.argmax(y_batch, axis=1)
    accuracy_cnt +=np.sum( p==t[i:i+batch_size])

print("Accuracy:" + str(float(accuracy_cnt) / len(x)))

Accuracy:0.9352
